import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Syne } from "next/font/google";
import "./globals.css";
import { Work_Sans, PT_Serif } from "next/font/google";
import TawkLayout from "./document";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const outfitFont = Outfit({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-outfit",
//   weight: ["200", "300", "400", "500", "600", "700", "800"],
// });

const syneFont = Syne({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-syne",
  weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syneFont.variable}`}>
        <TawkLayout />
        {children}
      </body>
    </html>
  );
}
